config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  

  <head>
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">My Portflio</a>

        <span class="navbar-toggle-icon"></span>
      </button> 
      <ul class="navbar-nav ml-auto">
      <% if !current_user %>
        <li class="nav-item">
         <a class="btn btn-outline-light nav-link" href="/users/sign_in">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-outline-light nav-link" href="/users/sign_up">Sign Up</a>
        </li>
      <% else %>
        <li class="nav-item">
        <a class="btn btn-outline-light nav-link" href="/projects/new">New Project</a>
        </li>  
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete,class:'btn btn-outline-light nav-link' %>
        </li>
      <% end %>
        </ul>
    </nav>
  </head>
  <%= yield %>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
div{
  overflow: hidden
}
</style>
</head>

<body>

<p id="notice"><%= notice %></p>

<div class="text-center">
  <p class="lead">This is my Portflio for the CS3300 project.</p>
</div>

<main role="main">
      
      <div class="album py-1 bg-light">
        <div class="container">
        <div class="text-center">
          <h1 class="display-4">Projects</h1>
        </div>
          <div class="row">
          <% @projects.each do |project| %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                <div class="test" style="height:40px">
                  <h3 class="card-text"<td><%= project.title %></td></h3>
                  </div>
                  <div class="test" style="height:145px"">
                  <p class="card-text"><td><%= project.description %></td></p>
                  </div>
                  <div class="d-flex justify-content-between align-items-center">
                    <%= link_to 'Show', project %>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>

    </main>
    </body>
    </html>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<main role="main">
      
      <div class="album py-1 bg-light">
        <div class="container">
        <div class="pricing-header text-center">
          <h1 class="display-4"><%= @project.title %></h1>
        </div>
          <div class="row">
            <div class="col-lg-12">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <h1 class="card-text"<%= @project.title %></h1>
                  <p class="card-text"><%= @project.description %></p>
                  <div class="d-flex justify-content-between align-items-center">
                  </div>
                </div>
              </div>
              <div class="btn-group">
              <% if current_user %>
              <%= link_to 'Back', projects_path %> |
              <%= link_to 'Edit', edit_project_path(@project) %> |
              <%= link_to 'Delete', project_path, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% else %>
              <%= link_to 'Back', projects_path %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      
    </main>